apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-payment
  name: svc-payment
spec:
  selector:
    app: paymentdeployment
  ports:
    - port: 8081
      protocol: TCP
#      targetPort: 8081
      nodePort: 31301
  type: NodePort